name: Build Status
on:
  [ pull_request, push, workflow_dispatch ]
jobs:
  build:
    name: Build fobnail-attester
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Checkout all submodules
        run: |
          git submodule update --init --recursive --checkout

      - name: Build
        run: |
          docker build -t fobnail/fobnail-attester .
          ./docker.sh build-attester
